const players = [
    { no: 1, name: "Beau Alvarez", pos: "C", year: "Junior", ht: "6'2\"", wt: "210 lbs", hometown: "Redondo Beach, Calif.", school: "Redondo Union HS", bt: "R/R", image: "images/1 Beau Alvarez.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 2, name: "Kyson Frost", pos: "RHP", year: "Junior", ht: "6'0\"", wt: "185 lbs", hometown: "Atlanta, Ga.", school: "Marist HS", bt: "R/R", image: "images/2 Kyson Frost.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 3, name: "Dalton Seeker", pos: "OF", year: "Junior", ht: "6'1\"", wt: "190 lbs", hometown: "Mooresville, Ind.", school: "Mooresville HS", bt: "L/L", image: "images/3 Dalton Seeker.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 4, name: "Bryce Ready", pos: "INF", year: "Freshman", ht: "6'2\"", wt: "220 lbs", hometown: "Murrysville, Pa.", school: "Franklin Regional HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 5, name: "KJ DeBarge", pos: "INF", year: "Junior", ht: "6'3\"", wt: "190 lbs", hometown: "Potomac, Md.", school: "Bullis HS", bt: "R/R", image: "images/5 KJ DeBarge.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 6, name: "Tanner Swain", pos: "INF", year: "Sophomore", ht: "6'5\"", wt: "240 lbs", hometown: "Syracuse, N.Y.", school: "Cicero-North Syracuse HS", bt: "R/R", image: "images/6 Tanner Swain.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 7, name: "Trey Favors", pos: "INF", year: "Freshman", ht: "5'10\"", wt: "175 lbs", hometown: "San Diego, Calif.", school: "St. Augustine HS", bt: "L/R", image: "images/7 Trey Favors.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 8, name: "Matt Pennington", pos: "INF", year: "Junior", ht: "6'0\"", wt: "200 lbs", hometown: "Rockaway, N.J.", school: "Morris Knolls HS", bt: "R/R", image: "images/8 Matt Pennington.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 9, name: "Walker Mendez", pos: "INF", year: "Sophomore", ht: "5'10\"", wt: "190 lbs", hometown: "Wayne, N.J.", school: "Wayne Hills HS", bt: "L/R", image: "images/9 Walker Mendez.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 10, name: "Kenneth Couture", pos: "UT", year: "Freshman", ht: "5'11\"", wt: "180 lbs", hometown: "Brooklyn, N.Y.", school: "Jefferson HS", bt: "L/L", image: "images/10 Kenneth Couture.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 11, name: "Khal Valdez", pos: "RHP", year: "Sophomore", ht: "6'4\"", wt: "205 lbs", hometown: "Naples, Fla.", school: "Gulf Coast HS", bt: "R/R", image: "images/11 Khal Valdez.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 12, name: "Reese Witherspoon", pos: "RHP", year: "Sophomore", ht: "6'1\"", wt: "195 lbs", hometown: "San Antonio, Texas", school: "Warren HS", bt: "R/R", image: "images/12 Reese Witherspoon.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 14, name: "RJ Zimbardo", pos: "C", year: "Freshman", ht: "5'11\"", wt: "180 lbs", hometown: "Fresno, Calif.", school: "Fresno HS", bt: "R/R", image: "images/14 RJ Zimbardo.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 15, name: "Michael Vu", pos: "OF", year: "Sophomore", ht: "5'10\"", wt: "180 lbs", hometown: "Las Vegas, Nev.", school: "Palo Verde HS", bt: "R/R", image: "images/15 Michael Vu.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 17, name: "Griffin Kuntz", pos: "OF", year: "Senior", ht: "6'1\"", wt: "190 lbs", hometown: "San Jose, Calif.", school: "Pioneer HS", bt: "L/L", image: "images/17 Griffin Kuntz.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 18, name: "Clayton Krauss", pos: "RHP", year: "Senior", ht: "6'5\"", wt: "225 lbs", hometown: "Fairfield, Conn.", school: "Fairfield Warde HS", bt: "R/R", image: "images/18 Clayton Krauss.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 19, name: "Blake Blanco", pos: "OF", year: "Sophomore", ht: "6'0\"", wt: "215 lbs", hometown: "Phoenix, Ariz.", school: "O'Connor HS", bt: "R/R", image: "images/19 Blake Blanco.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 21, name: "Carter	Sass", pos: "OF", year: "Freshman", ht: "6'1\"", wt: "180 lbs", hometown: "Suwanee, Ga.", school: "North Gwinnett HS", bt: "R/R", image: "images/21 Carter Sass.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 23, name: "Name", pos: "POS", year: "YR", ht: "6'0\"", wt: "200 lbs", hometown: "Hometown", school: "HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 24, name: "Name", pos: "POS", year: "YR", ht: "6'0\"", wt: "200 lbs", hometown: "Hometown", school: "HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 25, name: "Name", pos: "POS", year: "YR", ht: "6'0\"", wt: "200 lbs", hometown: "Hometown", school: "HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 26, name: "Name", pos: "POS", year: "YR", ht: "6'0\"", wt: "200 lbs", hometown: "Hometown", school: "HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 27, name: "Name", pos: "POS", year: "YR", ht: "6'0\"", wt: "200 lbs", hometown: "Hometown", school: "HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 29, name: "Name", pos: "POS", year: "YR", ht: "6'0\"", wt: "200 lbs", hometown: "Hometown", school: "HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 31, name: "Name", pos: "POS", year: "YR", ht: "6'0\"", wt: "200 lbs", hometown: "Hometown", school: "HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 32, name: "Name", pos: "POS", year: "YR", ht: "6'0\"", wt: "200 lbs", hometown: "Hometown", school: "HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 33, name: "Name", pos: "POS", year: "YR", ht: "6'0\"", wt: "200 lbs", hometown: "Hometown", school: "HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 34, name: "Name", pos: "POS", year: "YR", ht: "6'0\"", wt: "200 lbs", hometown: "Hometown", school: "HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 35, name: "Name", pos: "POS", year: "YR", ht: "6'0\"", wt: "200 lbs", hometown: "Hometown", school: "HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 36, name: "Name", pos: "POS", year: "YR", ht: "6'0\"", wt: "200 lbs", hometown: "Hometown", school: "HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 37, name: "Name", pos: "POS", year: "YR", ht: "6'0\"", wt: "200 lbs", hometown: "Hometown", school: "HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 38, name: "Name", pos: "POS", year: "YR", ht: "6'0\"", wt: "200 lbs", hometown: "Hometown", school: "HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 39, name: "Name", pos: "POS", year: "YR", ht: "6'0\"", wt: "200 lbs", hometown: "Hometown", school: "HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
    { no: 40, name: "Name", pos: "POS", year: "YR", ht: "6'0\"", wt: "200 lbs", hometown: "Hometown", school: "HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        bioLink: 'http://bratinstitute.com'},
];
